apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hvh2yehul-python 
  janus-idp.io/tekton: hvh2yehul-python
  backstage.io/kubernetes-id: hvh2yehul-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hvh2yehul-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  